apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage
  labels:
    app.kubernetes.io/name: landingpage
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: landingpage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: landingpage
    spec:
      containers:
        - name: landingpage
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always