replicaCount: 1

image:
  repository: "OPENSHIFT_REGISTRY_URL/NAMESPACE/landingpage"
  tag: "IMAGE_TAG"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
