replicaCount: 1

image:
  repository: ghcr.io/bcgov/abi-landing-page
  tag: dev
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
